### ISSUE TITLE
FatalErrorException in AssetsExtension.php line 9: Parse Error: syntax error, unexpected '['

### ISSUE THREAD

**Issue by zanshee** [andrey1s/TwitterBootstrapBundle#4]
twitter/bootstrap-bundle/Twitter/BootstrapBundle/Twig/AssetsExtension.php:

class AssetsExtension extends \Twig_Extension
{
    /** @var array */
    private $assets = [];
    /** @var \Symfony\Bundle\TwigBundle\Extension\AssetsExtension */
    private $extension;
    /** @var array */
    private $pattern = [
        'stylesheets' => '<link href="{{ value }}" rel="stylesheet" type="text/css"/>',
        'javascripts' => '<script src="{{ value }}" type="text/javascript"></script>'
    ];

must be

class AssetsExtension extends \Twig_Extension
{
    /** @var array */
    private $assets = array();
    /** @var \Symfony\Bundle\TwigBundle\Extension\AssetsExtension */
    private $extension;
    /** @var array */
    private $pattern = array(
        'stylesheets' => '<link href="{{ value }}" rel="stylesheet" type="text/css"/>',
        'javascripts' => '<script src="{{ value }}" type="text/javascript"></script>'
    );

PHP Version 5.3.10-1ubuntu3.15

**Comment by pedroresende** [comment]
@zanshee the problem is you PHP version, from 5.4+ array() has been changed by []

**Comment by andrey1s** [comment]
fixed version 1.3.2
